include ../../../../make.inc

#OBJS = slab.o slabwall.o slabdisp.o slabmode.o slaboverlap.o

#all: $(OBJS)

#slab.o: slab.cpp slab.h ../../../defs.h ../../../waveguide.h \
#	../../../material.h ../../../expression.h ../../../util/index.h
#	$(CC) $(FLAGS) -c slab.cpp

#slabwall.o: slabwall.cpp slabwall.h ../../../defs.h ../../../waveguide.h \
#	../../../material.h
#	$(CC) $(FLAGS) -c slabwall.cpp

#slabdisp.o: slabdisp.cpp slabdisp.h ../../../defs.h ../../../waveguide.h \
#	../../../material.h
#	$(CC) $(FLAGS) -c slabdisp.cpp

#slabmode.o: slabmode.cpp slabmode.h slab.h ../../../defs.h ../../../mode.h
#	$(CC) $(FLAGS) -c slabmode.cpp

#slaboverlap.o: slaboverlap.cpp slaboverlap.h slab.h ../../../defs.h \
#	../../../mode.h
#	$(CC) $(FLAGS) -c slaboverlap.cpp

FORCE:

clean:
	-rm *.a *.o core *~
